apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
- ../webhook

patchesStrategicMerge:
- manager_webhook_patch.yaml
- webhookcainjection_patch.yaml
- webhookservicecainjection_patch.yaml
