apiVersion: v1
kind: Namespace
metadata:
  name: system
  annotations:
    # Allow pods carrying the target.workload.openshift.io/management annotation
    # to be handled by OpenShift Workload Partitioning.
    workload.openshift.io/allowed: management
  labels:
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
